Fix verify stage when specify path
semantic-release/wordpress pull request #197
Opened 2023-12-25 21:35 UTC by AntoninoBonanno

I fixed the verify stage (both for the theme and for the plugin) in case the path is specified from the configuration, Resolve #159 .

I also added "path" in the README.md as I believe it is a useful feature when your code is in a subdirectory or is generated by Webpack as in my case

2024-01-16 14:22 UTC, seebeen requested changes
Let's sort out the dependency bumps in the commit - and we can merge then.

Awseome work, btw. Much appreciated.

2024-01-16 14:22 UTC, seebeen commented on package.json
Did you update the dependencies manually?

2024-01-16 17:37 UTC, AntoninoBonanno commented on package.json
i used [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)

2024-01-16 18:17 UTC, seebeen commented on package.json
Can you remove them from the commit please, and we can merge

2024-01-17 13:39 UTC, seebeen approved these changes
All good  💪

2024-01-17 13:45 UTC, seebeen commented
Hey, I just saw that none of the commits are GPG signed. Would it be too much of a hassle to [setup GPG](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification) on your end.

After that, you can use [this guide](https://webdevstudios.com/2020/05/26/retroactively-sign-git-commits/) To retroactively sign your commits in this PR.

Reason the GPG signing is enforced in this repo is to prevent potential supply chain attacks.  
WordPress powers >45% of all the websites in the world so the poential impact of supply chain poisoning is immense.

2024-01-17 22:26 UTC, AntoninoBonanno commented
ready

2024-01-18 03:21 UTC, merged